name: ramabook
description: A modern book management app with Persian fonts and Starry Night design
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  animated_background: ^2.0.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/README.txt
    - assets/audio/READMEE.txt

  fonts:
    - family: B-Koodak
      fonts:
        - asset: fonts/persian_fonts/B-Koodak.TTF
    - family: B-NAZANIN
      fonts:
        - asset: fonts/persian_fonts/B-NAZANIN.TTF
    - family: B-Yekan
      fonts:
        - asset: fonts/persian_fonts/B-Yekan.ttf
    - family: Dana-Bold
      fonts:
        - asset: fonts/persian_fonts/Dana-Bold.ttf
    - family: Dana-Regular
      fonts:
        - asset: fonts/persian_fonts/Dana-Regular.ttf
    - family: Shabnam-Bold
      fonts:
        - asset: fonts/persian_fonts/Shabnam-Bold.ttf
    - family: Shabnam-Regular
      fonts:
        - asset: fonts/persian_fonts/Shabnam-Regular.ttf
    - family: Vazir-Regular
      fonts:
        - asset: fonts/persian_fonts/Vazir-Regular.ttf
