name: Flutter Build (Android & Web)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Clean previous builds
      - name: Clean previous builds
        run: flutter clean

      # 5. Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # 6. Build Android App Bundle (AAB)
      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      # 7. Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # 8. Upload Android APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 9. Upload Android AAB
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      # 10. Upload Web Build
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web
