- name: Check and Auto-Fix Android v1 embedding
  run: |
    echo "Scanning for old Android v1 embedding..."
    FOUND_V1=0

    for f in $(find android/app/src/main/java android/app/src/main/kotlin \( -name "*.java" -o -name "*.kt" \) -type f); do
      if grep -q "io.flutter.app.FlutterActivity" "$f"; then
        echo "⚠️ Replacing old FlutterActivity in $f"
        sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' "$f"
        FOUND_V1=1
      fi
      if grep -q "GeneratedPluginRegistrant.registerWith" "$f"; then
        echo "⚠️ Removing GeneratedPluginRegistrant.registerWith in $f"
        sed -i '/GeneratedPluginRegistrant\.registerWith/d' "$f"
        FOUND_V1=1
      fi
    done

    if [ "$FOUND_V1" -eq 1 ]; then
      echo "✅ Old v1 embedding found and auto-fixed."
    else
      echo "✅ No old embedding found. Safe to build."
    fi
