name: Flutter Auto Build & Fix v1 Embedding

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flutter-fix-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'

      - name: Backup project outside workspace
        run: |
          BACKUP_DIR="/home/runner/work/backups/backup_$(date +%Y-%m-%d_%H-%M)"
          mkdir -p "$BACKUP_DIR"
          cp -r "$GITHUB_WORKSPACE/." "$BACKUP_DIR"
          echo "✅ Backup saved at $BACKUP_DIR"

      - name: Check and Auto-Fix Android v1 embedding
        run: |
          FOUND_V1=0
          # اصلاح کدهای Java/Kotlin
          for f in $(find android -type f \( -name "*.java" -o -name "*.kt" \)); do
            if grep -q "io.flutter.app.FlutterActivity" "$f"; then
              echo "⚠️ Replacing old FlutterActivity in $f"
              sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' "$f"
              FOUND_V1=1
            fi
            if grep -q "GeneratedPluginRegistrant.registerWith" "$f"; then
              echo "⚠️ Removing GeneratedPluginRegistrant.registerWith in $f"
              sed -i '/GeneratedPluginRegistrant\.registerWith/d' "$f"
              FOUND_V1=1
            fi
          done

          # اصلاح build.gradle
          BUILD_FILE="android/app/build.gradle"
          if [ -f "$BUILD_FILE" ]; then
            echo "🔧 Checking $BUILD_FILE ..."
            sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 34/' "$BUILD_FILE"
            sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 34/' "$BUILD_FILE"
            sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 23/' "$BUILD_FILE"
            FOUND_V1=1
          fi

          # اصلاح AndroidManifest.xml
          for manifest in $(find android/app/src/main -name "AndroidManifest.xml"); do
            if grep -q "io.flutter.app.FlutterApplication" "$manifest"; then
              echo "⚠️ Removing FlutterApplication in $manifest"
              sed -i '/io.flutter.app.FlutterApplication/d' "$manifest"
              FOUND_V1=1
            fi
          done

          if [ "$FOUND_V1" -eq 1 ]; then
            echo "✅ Old v1 embedding and configs fixed."
          else
            echo "✅ No v1 embedding found. Safe to build."
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build AppBundle
        run: flutter build appbundle --release --no-tree-shake-icons

      - name: Commit & Push Auto-Fixes
        if: steps.flutter-fix-build.outcome == 'success'
        run: |
          git config user.name "zohre265"
          git config user.email "zorama70@gmail.com"
          git add .
          git commit -m "Auto-fix: Migrated Android v1 embedding + SDK updates" || echo "No changes to commit"
          git push origin main || echo "Push failed, check token and permissions"
