name: Flutter Build (Android & Web - Logs to File)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 3. Install dependencies with verbose logging
      - name: Install dependencies
        run: flutter pub get -v

      # 4. Clean previous builds
      - name: Clean previous builds
        run: flutter clean

      # 5. Analyze code and save logs
      - name: Flutter Analyze (save logs)
        run: |
          mkdir -p build_logs
          flutter analyze --fatal-warnings --no-fatal-infos -v > build_logs/flutter_analyze.log 2>&1 || true

      # 6. Build Android APK and save logs
      - name: Build Android APK (save logs)
        run: |
          mkdir -p build_logs
          flutter build apk --release -v > build_logs/flutter_apk.log 2>&1 || true

      # 7. Build Android App Bundle (AAB) and save logs
      - name: Build Android AAB (save logs)
        run: |
          mkdir -p build_logs
          flutter build appbundle --release -v > build_logs/flutter_aab.log 2>&1 || true

      # 8. Build Flutter Web and save logs
      - name: Build Flutter Web (save logs)
        run: |
          mkdir -p build_logs
          flutter build web --release -v > build_logs/flutter_web.log 2>&1 || true

      # 9. Upload build artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web

      # 10. Upload all logs
      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-logs
          path: build_logs/

