name: Flutter Build

on:
  workflow_dispatch: # اجرای دستی از تب Actions
  push:
    branches:
      - main  # هر بار که روی main push کنی هم اجرا میشه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # آخرین نسخه stable فلان

      - name: Install dependencies
        run: flutter pub get

      # ---------- Build Android AAB ----------
      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload Android AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

      # ---------- Build Web ----------
      - name: Build Web
        run: flutter build web --release

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
